### PR TITLE
[chore] Create Ukrainian translate 

### PR DESCRIPTION
**Pull request by lyaschuchenko**
# [chore] Create Ukrainian translate

Translate to Ukrainian, some rows. Again

## PR Checklist

- [x] I've started from master
- [x] I've only committed changes related to this PR
- [x] All tests pass
- [x] I've removed all commented code

### CODE REVIEW

**Comment by Larsluph** [comment]
Please request access to Tolgee to edit translations.

**Comment by lyaschuchenko** [comment]
> Please request access to Tolgee to edit translations.

how?

**Comment by Larsluph** [comment]
> how?

Everything is in the Contributing Guidelines, you can request an invite through the Discord server.

**Comment by Larsluph** [comment]
I just imported your file so that you don't have to start over.

**Pull request closed without merging**
