### PR TITLE
chore: update translations

### PR DESCRIPTION
**Pull request by tainewoo**
chore: update translations

update translations for zh-Hans and zh-Hant, for new added parameters of rss rule.

### CODE REVIEW

**Comment by WDaan** [comment]
@Larsluph won't this be overriden in the next Tolgee translation sync?

**Comment by Larsluph** [comment]
> @Larsluph won't this be overriden in the next Tolgee translation sync?

Yes it will, all translation updates must be made in Tolgee. The files here are only for reference as even when building the app from the CI we fetch latest data from Tolgee, overriding every changes.

**Comment by tainewoo** [comment]
Hi @WDaan and @Larsluph ,

sorry I can't access the discord, maybe I can move the changes to tolgee, or just wait someone else t o copy the changes to tolgee.

**Comment by tainewoo** [comment]
Because I can't access discord, maybe it's better to wait for the locale updates later.
Let me close this PR.

**Comment by WDaan** [comment]
Yeah unfortunately we cannot paste a public tolgee invite link, it must be one specifically for you that we sent over DM.

**Comment by Larsluph** [comment]
@tainewoo 
I just imported your changes to Tolgee and sent you an email with an invitation link.

**Comment by tainewoo** [comment]
Thank you so much @WDaan and @Larsluph , I just got the invitation and joined the project.
Hope I can contribute in more ways :)

**Pull request closed without merging**
